### ISSUE TITLE
Beam Stream commands do not work

### ISSUE THREAD

**Issue by ibigfire** [Kwoth/NadekoBot#630]
When using the ~beam command it does not notify when that streamer goes online.  I suspect it is related to the ~checkbeam command always returning "Streamer 0 is online." regardless of which streamer username I input.

**Comment by Kwoth** [comment]
Fixed in the latest push. Will be in the next release.

**Comment by ibigfire** [comment]
This is still not working and I have updated Nadeko.  It does now say "Streamer ibigfire is offline." when checking the Beam stream, but it will always say I am offline whether I am online or not.
